### ISSUE TITLE
Why the -=- for perterb in algos/bp.py?

### ISSUE THREAD

**Issue by Erotemic** [shibhansh/loss-of-plasticity#1]
I'm curious if there is a reason for doing -=- rather than just += on the normal noise in `perterb` on line: https://github.com/shibhansh/loss-of-plasticity/blob/main/lop/algos/bp.py#L54

It's done elsewhere too including the gnt code.

Is there some numerical stability thing I'm not aware of, or is this just a quirk of the implementation that I can ignore?

**Comment by shibhansh** [comment]
Hey, sorry about the late reply. For some reason, I didn't get notification about the issues on this repository.

It's just a quirk of the implementation that you can ignore. We will probably remove it soon so it doesn't cause more confusion.
