### ISSUE TITLE
initialization permuted mnist

### ISSUE THREAD

**Issue by EvelyneCalista** [shibhansh/loss-of-plasticity#3]
Hi Shibhansh,

I have a question regarding the permuted mnist experiment, in DeepFFNN.py Line 28 you change the nonlinearity as the self.act_type
 _nn.init.kaiming_uniform_ _ _(self.fc.weight, nonlinearity=self.act_type)_

However Kaiming not supported ELU and SiLU non linearity, how can you choose the nonlinearity type by relu for those two nonlinearities.

Thank you.

**Comment by shibhansh** [comment]
Hey Evelyne,

Hey, sorry about the late reply. For some reason, I didn't get notification about the issues on this repository.
I chose relu for those two non-linearity as that is what the original papers did [1, 2]. You're correct that choosing relu is not the perfect thing and it can be improved.
[1] Ramachandran, P., Zoph, B. & Le, Q. V. Searching for activation functions. In 6th International Conference on Learning
Representations, May 3, 2018, Workshop Track Proceedings (OpenReview.net, 2018).
[2] Clevert, D., Unterthiner, T. & Hochreiter, S. Fast and accurate deep network learning by exponential linear units (elus).
In 4th International Conference on Learning Representations (2016).
