### ISSUE TITLE
scipy==1.11.2 is unavailable for Python 3.8

### ISSUE THREAD

**Issue by tkella47** [shibhansh/loss-of-plasticity#6]
Description:
I'm currently unable to install scipy==1.11.2 in a Python 3.8 environment. When attempting installation, I receive an error indicating that a compatible version cannot be found. 

Steps to Reproduce:

Set up a Python 3.8 virtual environment.
Run pip install scipy==1.11.2.
Observe the installation error due to version incompatibility.

Please advise on version used for reproduction

**Comment by shibhansh** [comment]
Thank you for pointing out the issue. The scipy package is not important for the main results in the package. You can use an older version.
